eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-domain1
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
config:
  env:  dev
feign:
  sentinel:
    enabled: true