eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: service-gateway
zuul:
  routes:
    service-base: /apigateway/**
